apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hiqode-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingress.scheme }}
    alb.ingress.kubernetes.io/target-type: {{ .Values.ingress.targetType }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/healthcheck-path: {{ .Values.ingress.healthcheckPath }}
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /order
            pathType: Prefix
            backend:
              service:
                name: order-service
                port:
                  number: {{ .Values.order.port }}
          - path: /payment
            pathType: Prefix
            backend:
              service:
                name: payment-service
                port:
                  number: {{ .Values.payment.port }}
          - path: /                        # ← MUST be last
            pathType: Prefix
            backend:
              service:
                name: login-service
                port:
                  number: {{ .Values.login.port }}