apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: payment-app
  ports:
    - protocol: TCP
      port: {{ .Values.payment.port }}
      targetPort: {{ .Values.payment.port }}
  type: ClusterIP